name: publish
on: [push]
env:
  CARGO_TERM_COLOR: always
  # CONTAINER_REGISTRY: quay.io
  # CONTAINER_REPOSITORY: patrickdung/docker-images-goatcounter
  CONTAINER_REGISTRY: ghcr.io
  # ## GH Repository must be lower case, when using in GH action
  CONTAINER_REPOSITORY: ${{ github.repository }}
  ORIGINAL_SOURCECODE_URL: https://github.com/cristianovisk/regvuln
jobs:
  regvuln_docker:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.PUSH_DOCKER_IMAGE_REGVULN }}
      - name: Build and push to container registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            RELEASE_VERSION=latest
            LABEL_IMAGE_URL=${{ env.ORIGINAL_SOURCECODE_URL }}
            LABEL_IMAGE_SOURCE=https://github.com/${{ github.repository }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ needs.init-env.outputs.container_registry_base_uri }}:latest