name: publish
on: [push]
jobs:
  regvuln_docker:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: cristianovisk
         password: ${{ secrets.PUSH_DOCKER_IMAGE_REGVULN }}
     - name: Build the regvuln Docker image
       run: |
         docker build . --tag ghcr.io/cristianovisk/regvuln:latest
         docker push ghcr.io/cristianovisk/regvuln:latest