name: Docker Release

on:
  push:
    tags:
      - "v*"

env:
  SH8: $(echo ${GITHUB_SHA} | cut -c1-8)
  TAG: $(git tag | tail -n 1)

jobs:
  release:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_DOCKER_IMAGE_REGVULN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            cristianovisk/regvuln
            ghcr.io/${{ github.repository }}
      
      - run: |
          echo "SH8=$(echo ${{ env.SH8 }})" >> $GITHUB_ENV
        name: Get short commit

      - run: |
          echo "TAG=$(echo ${{ env.TAG }})" >> $GITHUB_ENV
        name: Get last TAG commit

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/regvuln:latest
            ${{secrets.DOCKERHUB_USERNAME}}/regvuln:${{ env.SH8 }}
            ${{secrets.DOCKERHUB_USERNAME}}/regvuln:${{ env.TAG }}
            ghcr.io/${{secrets.DOCKERHUB_USERNAME}}/regvuln:latest
            ghcr.io/${{secrets.DOCKERHUB_USERNAME}}/regvuln:${{ env.TAG }}
            ghcr.io/${{secrets.DOCKERHUB_USERNAME}}/regvuln:${{ env.SH8 }}